modules/Menu/Http/routes.php
<?php
    Route::group([
        'prefix'     => 'fatorcms',
        'middleware' => [
            'auth',
            'acl',
            'cms'
        ],
        'namespace'  => 'Modules\Menu\Http\Controllers'
    ], function () {
        Route::resource('menu', 'MenuController');
        Route::patch('menu/status/{id}', [
            'as'   => 'fatorcms.menu.status',
            'uses' => 'MenuController@status'
        ]);
    });

modules/Menu/Entities/Menu.php
<?php namespace Modules\Menu\Entities;

use App\BaseModel;
use Illuminate\Support\Facades\Auth;
use Modules\Acl\Entities\Action;

class Menu extends BaseModel
{

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'url',
        'user_id',
        'status',
        'parent_id',
        'route',
        'seo_url',
        'icon_id',
        'filename',
        'attribute',
        'description',
        'order'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent()
    {
        return $this->belongsTo('Modules\Menu\Entities\Menu', 'parent_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function parents()
    {
        return $this->hasMany('Modules\Menu\Entities\Menu', 'parent_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function icon()
    {
        return $this->belongsTo('App\Icon', 'icon_id');
    }


    /**
     * @param int $status
     * @return mixed
     */
    public static function getMenu($status = 1)
    {
        if (Auth::user() && !Auth::user()->isAdmin()) {
            $menu = Menu::with([
                'parents' => function ($q) use ($status) {
                    $q->whereIn('route', Auth::user()->getActions())->whereStatus($status)->orderBy('order', 'asc');
                }
            ])->whereParentId(0)->whereStatus($status)->orderBy('order', 'asc')->get();
        } else {
            $menu = Menu::with('parent')->whereParentId(0)->whereStatus($status)->orderBy('order', 'asc')->get();
        }
        return $menu;
    }

}

modules/Menu/Http/Controllers/MenuController.php
<?php namespace Modules\Menu\Http\Controllers;

use App\Http\Controllers\BaseModuleController;
use App\Icon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str;
use Modules\Acl\Entities\Action;
use Modules\Menu\Entities\Menu;
use Modules\Menu\Http\Requests\MenuRequest;

class MenuController extends BaseModuleController
{

    /**
     * Compartilha com as views um array de select do parents (menus) e icones da tabela icons
     */
    public function lists()
    {
        $routes = Action::all()->lists('route', 'route')->toArray();
        $parents = Menu::all()->lists('name', 'id')->toArray();
        $icons = Icon::all()->lists('icon', 'id')->toArray();
        View::share(compact('parents', 'icons', 'routes'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $list = Menu::with([
            'parents' => function ($q) {
                if (!Auth::user()->isAdmin()) {
                    $q->whereIn('route', Auth::user()->getActions())->orderBy('order', 'asc');
                }
            }
        ])->whereParentId(0)->orderBy('order', 'asc')->paginate(10);
        return view('menu::index', compact('list'));
    }

    /**
     * @return View
     */
    public function create()
    {
        $this->lists();
        return view('menu::create');
    }

    /**
     * @param MenuRequest $request
     * @return \Illuminate\Http\RedirectResponse
     * Recebe o request do formulário do menu (apenas novos inserts) METODO POST
     */
    public function store(MenuRequest $request)
    {
        $request->merge([
            'seo_url' => Str::slug($request->get('name'), '-'),
            'user_id' => Auth::user()->id
        ]);
        Menu::create($request->except(['_token']));
        return redirect()->route('fatorcms.menu.index')->with('success', trans('messages.insert.success'));
    }

    /**
     * @param $id
     * @return View
     */
    public function edit($id)
    {
        $this->lists();
        $edit = Menu::findOrFail($id);
        return view('menu::edit', compact('edit'));
    }

    /**
     * @param MenuRequest $request
     * @param             $id
     * @return \Illuminate\Http\RedirectResponse
     * Recebe o request do formulário do menu (apenas atualizações) METODO PATCH
     */
    public function update(MenuRequest $request, $id)
    {
        $request->merge([
            'seo_url' => Str::slug($request->get('name'), '-'),
            'user_id' => Auth::user()->id
        ]);
        $update = Menu::with('icon')->findOrFail($id);
        $update->update($request->except(['_token']));
        return redirect()->route('fatorcms.menu.index')->with('success', trans('messages.update.success'));
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * Ativa ou Inativa o menu
     */
    public function status($id)
    {
        $status = Menu::findOrFail($id);
        $to = ($status->status) ? 0 : 1;
        $status->status = $to;
        $status->save();
        return redirect()->route('menu.index')->with('success', trans('messages.status.success', [
            'status' => ($to) ? trans('dictionary.status_text.active') : trans('dictionary.status_text.inactive')
        ]));
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * Deleta o registro do banco de dados
     */
    public function destroy($id)
    {
        Menu::destroy($id);
        return redirect()->route('fatorcms.menu.index')->with('success', trans('messages.delete.success'));
    }

}

modules/Menu/Resources/views/create.blade.php
@extends('layouts.cms')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h4 class="panel-title">{!! trans('dictionary.create') !!} Menu</h4>
                <p>{!! trans('messages.form.alert.fields_required') !!}</p>
            </div>
        </div>
        {!! Form::open(['route' => 'fatorcms.menu.store']) !!}
        @include('menu::form')
        {!! Form::close() !!}
    </div>
@endsection

modules/Menu/Resources/views/edit.blade.php
@extends('layouts.cms')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h4 class="panel-title">{!! trans('dictionary.edit') !!} Menu</h4>
                <p>{!! trans('messages.form.alert.fields_required') !!}</p>
            </div>
        </div>
        {!! Form::model($edit, ['route' => ['fatorcms.menu.update', $edit->id], 'method' => 'PATCH']) !!}
        @include('menu::form')
        {!! Form::close() !!}
    </div>
@endsection

modules/Menu/Resources/views/form.blade.php
<div class="col-lg-6">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <div class="form-group">
                <label for="status"
                       class="control-label">{!! trans('dictionary.status') !!}</label>
                <br/>

                <div class="radio radio-success radio-inline">
                    {!! Form::radio('status', 1, true) !!}
                    <label for="radio4">
                        {!! trans('dictionary.status_text.active') !!}
                    </label>
                </div>
                <div class="radio radio-danger radio-inline">
                    {!! Form::radio('status', 0, false) !!}
                    <label for="radio4">
                        {!! trans('dictionary.status_text.inactive') !!}
                    </label>
                </div>
            </div>

            <div class="form-group {!! ($errors->first('name')) ? 'has-error' : '' !!}">
                <label for="name">{!! trans('menu::db.name'). ' (*)' !!}</label>
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('menu::db.name'). ' (*)', 'required' => 'required']) !!}
                {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
            </div>

            <div class="form-group {!! ($errors->first('route')) ? 'has-error' : '' !!}">
                <label for="parent_id">
                    {!! trans('menu::db.route') !!} ({!! trans('dictionary.optional') !!})
                </label>
                {!! Form::select('route', ['' => trans('dictionary.select', ['name' => trans('menu::db.route')])] + $routes, null, ['class' => 'form-control', 'id' => 'select']) !!}
                {!! $errors->first('route', '<span class="help-block">:message</span>') !!}
            </div>

            <div class="form-group {!! ($errors->first('url')) ? 'has-error' : '' !!}">
                <label for="url">
                    Params
                </label>
                {!! Form::text('url', null, ['class' => 'form-control']) !!}
                {!! $errors->first('url', '<span class="help-block">:message</span>') !!}
            </div>

            <div class="form-group {!! ($errors->first('filename')) ? 'has-error' : '' !!}">
                <label for="filename">{!! trans('menu::db.filename') !!} ({!! trans('dictionary.optional') !!}
                    )</label>
                {!! Form::file('filename', ['class' => 'form-control']) !!}
                {!! $errors->first('filename', '<span class="help-block">:message</span>') !!}
            </div>
        </div>
    </div>
</div>

<div class="col-lg-6">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <div class="form-group {!! ($errors->first('parent_id')) ? 'has-error' : '' !!}">
                <label for="parent_id">Menu ({!! trans('dictionary.optional') !!})</label>
                {!! Form::select('parent_id', ['' => trans('dictionary.select', ['name' => 'menu'])] + $parents, null, ['class' => 'form-control', 'id' => 'select']) !!}
                {!! $errors->first('parent_id', '<span class="help-block">:message</span>') !!}
            </div>

            <div class="form-group {!! ($errors->first('attribute')) ? 'has-error' : '' !!}">
                <label for="attribute">{!! trans('menu::db.attribute') !!}
                    ({!! trans('dictionary.optional') !!})
                </label>
                {!! Form::text('attribute', null, ['class' => 'form-control', 'placeholder' => trans('menu::db.attribute')]) !!}
                {!! $errors->first('attribute', '<span class="help-block">:message</span>') !!}
            </div>

            <div class="form-group {!! ($errors->first('icon_id')) ? 'has-error' : '' !!}">
                <label for="icon">{!! trans('menu::db.icon') !!} ({!! trans('dictionary.optional') !!})
                    <i id="brand"></i>
                </label>
                {!! Form::select('icon_id', ['' => trans('dictionary.icon')] + $icons, null, ['class' => 'form-control', 'id' => 'select-icon']) !!}
                {!! $errors->first('icon_id', '<span class="help-block">:message</span>') !!}
            </div>

            <div class="form-group {!! ($errors->first('order')) ? 'has-error' : '' !!}">
                <label for="order">
                    {!! trans('dictionary.order') !!} ({!! trans('dictionary.optional') !!})
                </label>
                {!! Form::text('order', null, ['class' => 'form-control', 'placeholder' => trans('dictionary.order'), 'required' => 'required']) !!}
                {!! $errors->first('order', '<span class="help-block">:message</span>') !!}
            </div>
        </div>
    </div>
</div>

<div class="col-lg-12 menu">
    <div class="ibox">
        <div class="ibox-content">
            <h2>{!! trans('menu::db.description') !!}</h2>
            {!! Form::textarea('description', null, ['id' => 'description', 'placeholder' => '...']) !!}
            {!! $errors->first('description', '<span class="help-block">:message</span>') !!}
            <button class="btn btn-success pull-right">{!! trans('menu::db.btn.submit') !!}</button>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

@section('cjs')
    {!! HTML::script('js/cms/scripts/menu/menu.js') !!}
@endsection

modules/Menu/Resources/views/index.blade.php
@extends('layouts.cms')

@section('content')
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <a href="{!! URL::route('fatorcms.menu.create') !!}"
               class="btn btn-success pull-right">
                {!! trans('dictionary.create') !!} Menu
            </a>

            <h2>Menus</h2>
        </div>
        <div class="ibox-content">

            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover datatable">
                    <thead>
                    <tr>
                        <th data-ref="name">{!! trans('menu::db.name') !!}</th>
                        <th data-ref="route">{!! trans('menu::db.route') !!}</th>
                        <th data-ref="seo_url">{!! trans('menu::db.seo_url') !!}</th>
                        <th data-ref="params">{!! trans('menu::db.attribute') !!}</th>
                        <th data-ref="status">{!! trans('dictionary.status') !!}</th>
                        <th data-ref="created_at">{!! trans('dictionary.created_at') !!}</th>
                        <th width="11%">{!! trans('dictionary.options') !!}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if ($list->count())
                        @foreach($list as $row)
                            <tr>
                                <td>{!! $row->name !!}</td>
                                <td>{!! $row->route !!}</td>
                                <td>{!! $row->seo_url !!}</td>
                                <td>{!! $row->attribute !!}</td>
                                <td>{!! $row->StatusText !!}</td>
                                <td>{!! $row->created_at !!}</td>
                                <td>
                                    <a class="btn btn-primary btn-xs pull-left margin-right"
                                       href="{!! URL::route('fatorcms.menu.edit', $row->id) !!}">
                                        <i class="fa fa-pencil"></i>
                                    </a>

                                    {!! Form::open(['route' => ['fatorcms.menu.status', $row->id], 'method' => 'PATCH', 'class' => 'form-horizontal pull-left']) !!}
                                    <button class="btn {!! ($row->status) ? 'btn-success' : 'btn-danger' !!} btn-xs margin-right"
                                            title="{!! $row->StatusText !!}">
                                        <i class="glyphicon {!! ($row->status) ? 'glyphicon-ok' : 'glyphicon-off' !!}"></i>
                                    </button>
                                    {!! Form::close() !!}

                                    @if ($row->parents->count())
                                    <button data-url="{!! URL::route('fatorcms.menu.destroy', $row->id) !!}"
                                            data-text="{!! ($row->parents->count()) ? trans('messages.delete.alert') : '' !!}"
                                            class="btn btn-danger btn-xs sweetBt-delete">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                    @else
                                        {!! Form::open(['route' => ['fatorcms.menu.destroy', $row->id], 'method' => 'DELETE', 'class' => 'form-horizontal pull-left']) !!}
                                        <button class="btn btn-danger btn-xs">
                                            <i class="fa fa-trash-o"></i>
                                        </button>
                                        {!! Form::close() !!}
                                    @endif
                                </td>
                            </tr>
                            @if ($row->parents->count())
                                @foreach($row->parents as $parent)
                                    <tr>
                                        <td>{!! $parent->name !!}</td>
                                        <td>{!! $parent->route !!}</td>
                                        <td>{!! $parent->seo_url !!}</td>
                                        <td>{!! $parent->attribute !!}</td>
                                        <td>{!! $parent->StatusText !!}</td>
                                        <td>{!! $parent->created_at !!}</td>
                                        <td>
                                            <a class="btn btn-primary btn-xs pull-left margin-right"
                                               href="{!! URL::route('fatorcms.menu.edit', $parent->id) !!}">
                                                <i class="fa fa-pencil"></i>
                                            </a>

                                            {!! Form::open(['route' => ['fatorcms.menu.status', $parent->id], 'method' => 'PATCH', 'class' => 'form-horizontal pull-left']) !!}
                                            <button class="btn {!! ($parent->status) ? 'btn-success' : 'btn-danger' !!} btn-xs margin-right"
                                                    title="{!! $parent->StatusText !!}">
                                                <i class="glyphicon {!! ($parent->status) ? 'glyphicon-ok' : 'glyphicon-off' !!}"></i>
                                            </button>
                                            {!! Form::close() !!}

                                            @if ($parent->parents->count())
                                                <button data-url="{!! URL::route('fatorcms.menu.destroy', $parent->id) !!}"
                                                        data-text="{!! ($parent->parents->count()) ? trans('messages.delete.alert') : '' !!}"
                                                        class="btn btn-danger btn-xs sweetBt-delete">
                                                <i class="fa fa-trash-o"></i>
                                                </button>
                                            @else
                                                {!! Form::open(['route' => ['fatorcms.menu.destroy', $row->id], 'method' => 'DELETE', 'class' => 'form-horizontal pull-left']) !!}
                                                <button class="btn btn-danger btn-xs">
                                                    <i class="fa fa-trash-o"></i>
                                                </button>
                                                {!! Form::close() !!}
                                            @endif
                                        </td>
                                    </tr>
                                    @if ($parent->parents->count())
                                        @foreach($parent->parents as $third)
                                            <tr>
                                                <td>{!! $third->name !!}</td>
                                                <td>{!! $third->route !!}</td>
                                                <td>{!! $third->seo_url !!}</td>
                                                <td>{!! $third->attribute !!}</td>
                                                <td>{!! $third->StatusText !!}</td>
                                                <td>{!! $third->created_at !!}</td>
                                                <td>
                                                    <a class="btn btn-primary btn-xs pull-left margin-right"
                                                       href="{!! URL::route('fatorcms.menu.edit', $third->id) !!}">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>

                                                    {!! Form::open(['route' => ['fatorcms.menu.status', $third->id], 'method' => 'PATCH', 'class' => 'form-horizontal pull-left']) !!}
                                                    <button class="btn {!! ($third->status) ? 'btn-success' : 'btn-danger' !!} btn-xs margin-right"
                                                            title="{!! $third->StatusText !!}">
                                                        <i class="glyphicon {!! ($third->status) ? 'glyphicon-ok' : 'glyphicon-off' !!}"></i>
                                                    </button>
                                                    {!! Form::close() !!}

                                                    {!! Form::open(['route' => ['fatorcms.menu.destroy', $row->id], 'method' => 'DELETE', 'class' => 'form-horizontal pull-left']) !!}
                                                        <button class="btn btn-danger btn-xs">
                                                        <i class="fa fa-trash-o"></i>
                                                    </button>
                                                    {!! Form::close() !!}
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                @endforeach
                            @endif
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7">Nenhum registro encontrado.</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
                @include('layouts.elements.paginator', ['paginator' => $list])
            </div>

        </div>
    </div>
@endsection