modules/Popup/Http/routes.php
<?php

Route::group([
    'prefix' => 'fatorcms',
    'middleware' => 'cms',
    'namespace' => 'Modules\Popup\Http\Controllers'
], function () {
    Route::resource('popup', 'PopupController');
});

modules/Popup/Entities/Popup.php
<?php namespace Modules\Popup\Entities;

use App\Events\ImageEvent;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Popup extends Model
{

    use SoftDeletes;

    protected $fillable = [
        'name', 'slug', 'image', 'url',
        'status', 'release_date', 'closed_date'
    ];
    
    public function setSlugAttribute($value)
    {
        if (!empty($value))
            $this->attributes['slug'] = str_slug($value);
    }

    public function setReleaseDateAttribute($value)
    {
        if (!empty($value) && typeDate($value))
            $this->attributes['release_date'] = dateToSql($value);
    }

    public function setClosedDateAttribute($value)
    {
        if (!empty($value) && typeDate($value))
            $this->attributes['closed_date'] = dateToSql($value);
    }

    public function setImageAttribute()
    {
        event(new ImageEvent(request(), ['path' => '/assets/popup/', 'sizes' => [['w' => '800', 'h' => '400'], ['w' => '100']]], 'image'));
        $this->attributes['image'] = json_encode(request('return_upload'));
    }

    public function getClosedDateAttribute($value)
    {
        if (!empty($value) && $value != '0000-00-00')
            return dateToSql($value, 'Y-m-d', 'd/m/Y');
        return null;
    }

    public function getReleaseDateAttribute($value)
    {
        if (!empty($value) && $value != '0000-00-00')
            return dateToSql($value, 'Y-m-d', 'd/m/Y');
        return null;
    }

    public function getImageAttribute($value)
    {
        if (!empty($value))
            return json_decode($value, true);
        return null;
    }
}

modules/Popup/Http/Controllers/PopupController.php
<?php namespace Modules\Popup\Http\Controllers;

use App\Http\Controllers\BaseModuleController;
use Illuminate\Support\Facades\File;
use Modules\Popup\Entities\Popup;
use Modules\Popup\Http\Requests\PopupRequest;

class PopupController extends BaseModuleController
{

    public function index(Popup $popup)
    {
        $rows = $popup->paginate(20);
        return view('popup::index', compact('rows'));
    }

    public function create()
    {
        return view('popup::create');
    }

    public function store(PopupRequest $popupRequest, Popup $popup)
    {
        $popupRequest->merge(['slug' => $popupRequest->get('name')]);
        if (!$popup->create($popupRequest->all())) {
            return redirect()->back()
                ->with('error', 'Ops, algo aconteceu no servidor, não foi possível salvar o Popup, tente novamente.');
        } else {
            return redirect()->back()
                ->with('success', 'Popup ' . $popupRequest->get('name') . ', foi criado com sucesso.');
        }
    }

    public function edit($id, Popup $popup)
    {
        $edit = $popup->find($id);
        if (!$edit)
            return redirect()->route('fatorcms.popup.index')->with('error', 'Registro não encontrado.');
        return view('popup::edit', compact('edit'));
    }

    public function update($id, PopupRequest $popupRequest)
    {
        $popup = new Popup();
        $edit = $popup->find($id);
        if (!$edit)
            return redirect()->route('fatorcms.popup.index')->with('error', 'Registro não encontrado.');
        if ($popupRequest->hasFile('image')) {
            foreach ($edit->image as $item) {
                if (File::exists(public_path('/assets/popup/' . $item))) {
                    File::delete(public_path('/assets/popup/' . $item));
                }
            }
        }
        if (!$edit->update($popupRequest->all())) {
            return redirect()->back()
                ->with('error', 'Ops, algo aconteceu no servidor, não foi possível salvar o Popup, tente novamente.');
        } else {
            return redirect()->back()
                ->with('success', 'Popup ' . $popupRequest->get('name') . ', foi alterado com sucesso.');
        }
    }

    public function destroy($id, Popup $popup)
    {
        $destroy = $popup->find($id);
        if (!$destroy)
            return redirect()->route('fatorcms.popup.index')->with('error', 'Registro não encontrado.');

        foreach ($destroy->image as $item) {
            if (File::exists(public_path('/assets/popup/' . $item))) {
                File::delete(public_path('/assets/popup/' . $item));
            }
        }

        if (!$destroy->delete()) {
            return redirect()->route('fatorcms.popup.index')->with('error', 'Ops, algo aconteceu no servidor, não foi possível deletar o Popup, tente novamente.');
        } else {
            return redirect()->route('fatorcms.popup.index')->with('success', 'Popup deletada com sucesso.');
        }
    }

}

modules/Popup/Resources/views/create.blade.php
@extends('layouts.cms')

@section('title')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Novo Popup</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{!! route('fatorcms.dashboard') !!}">Dashboard</a>
                </li>
                <li>
                    <a href="{!! route('fatorcms.course.index') !!}">Popup's</a>
                </li>
                <li class="active">
                    <strong>Novo Curso</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-12">
            <p>
                Todos os campos com <strong class="text-danger">(*)</strong> são obrigatórios.
            </p>
        </div>
    </div>

    <div class="row page-heading white-bg">
        <div class="col-lg-9">
            <br/>
            <a href="{!! route('fatorcms.popup.index') !!}"
               class="btn btn-warning">
                <i class="fa fa-arrow-left"></i> Voltar
            </a>
        </div>
    </div>
@endsection

@section('content')
    {!! Form::open(['route' => 'fatorcms.popup.store', 'files' => true]) !!}
    @include('popup::form')
    {!! Form::close() !!}
@endsection

modules/Popup/Resources/views/edit.blade.php
@extends('layouts.cms')

@section('title')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Editar Popup - {!! $edit->name !!}</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{!! route('fatorcms.dashboard') !!}">Dashboard</a>
                </li>
                <li>
                    <a href="{!! route('fatorcms.course.index') !!}">Popup's</a>
                </li>
                <li class="active">
                    <strong>Editar Popup - {!! $edit->name !!}</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-12">
            <p>
                Todos os campos com <strong class="text-danger">(*)</strong> são obrigatórios.
            </p>
        </div>
    </div>

    <div class="row page-heading white-bg">
        <div class="col-lg-9">
            <br/>
            <a href="{!! route('fatorcms.popup.index') !!}"
               class="btn btn-warning">
                <i class="fa fa-arrow-left"></i> Voltar
            </a>
        </div>
    </div>
@endsection

@section('content')
    {!! Form::model($edit, ['route' => ['fatorcms.popup.update', $edit->id], 'method' => 'PATCH', 'files' => true]) !!}
        @include('popup::form')
    {!! Form::close() !!}
@endsection

modules/Popup/Resources/views/form.blade.php
<div class="ibox">
    <div class="ibox-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group{!! $errors->first('image') ? ' has-error' : '' !!}">
                    <label for="file">
                        Imagem <strong class="text-danger">*</strong>
                    </label>
                    @if (isset($edit) && !is_null($edit->image))
                        <br />
                        <img src="{!! url('/assets/popup/'.$edit->image['w']) !!}" alt=""/>
                        {!! Form::file('image', ['class' => 'form-control']) !!}
                    @else
                        {!! Form::file('image', ['class' => 'form-control', 'required']) !!}
                    @endif
                    {!! $errors->first('image', '<span class="text-danger">:message</span>') !!}
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group{!! $errors->first('name') ? ' has-error' : '' !!}">
                    <label for="name">
                        Nome <strong class="text-danger">*</strong>
                    </label>
                    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nome', 'required']) !!}
                    {!! $errors->first('name', '<span class="text-danger">:message</span>') !!}
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group{!! $errors->first('url') ? ' has-error' : '' !!}">
                    <label for="name">
                        URl <strong class="text-danger">*</strong>
                    </label>
                    {!! Form::text('url', null, ['class' => 'form-control', 'placeholder' => 'URl', 'required']) !!}
                    {!! $errors->first('url', '<span class="text-danger">:message</span>') !!}
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group{!! $errors->first('release_date') ? ' has-error' : '' !!}">
                    <label for="release_date">
                        Data de lançamento <strong class="text-success">(Opcional)</strong>
                    </label>
                    {!! Form::text('release_date', null, ['class' => 'form-control date-mask s-datepicker', 'placeholder' => 'Data de lançamento']) !!}
                    {!! $errors->first('release_date', '<span class="text-danger">:message</span>') !!}
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group{!! $errors->first('closed_date') ? ' has-error' : '' !!}">
                    <label for="closed_date">
                        Data de encerramento <strong class="text-success">(Opcional)</strong>
                    </label>
                    {!! Form::text('closed_date', null, ['class' => 'form-control date-mask s-datepicker', 'placeholder' => 'Data de encerramento']) !!}
                    {!! $errors->first('closed_date', '<span class="text-danger">:message</span>') !!}
                </div>
            </div>
        </div>
    </div>
</div>

<hr/>

<div class="ibox">
    <div class="ibox-content">
        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-check"></i> Salvar
                </button>
            </div>
        </div>
    </div>
</div>

modules/Popup/Resources/views/index.blade.php
@extends('layouts.cms')

@section('title')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Popup</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{!! route('fatorcms.dashboard') !!}">Dashboard</a>
                </li>
                <li class="active">
                    <strong>Popup</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="row page-heading white-bg">
        <div class="col-lg-9">
            <br/>
            <a href="{!! URL::route('fatorcms.popup.create') !!}" class="btn btn-success">
                <i class="fa fa-plus"></i> Nova Pop UP
            </a>
        </div>
    </div>
@endsection

@section('content')

    <div class="col-lg-12">
        <div class="ibox-content">
            <table class="table table-hover table-stripped">
                <thead>
                <tr>
                    <td>#Cód</td>
                    <td>Nome</td>
                    <td>URl</td>
                    <td>Data de lançamento</td>
                    <td>Data de encerramento</td>
                    <td>#</td>
                </tr>
                </thead>
                <tbody>
                @foreach($rows as $row)
                    <tr>
                        <td>{!! $row->id !!}</td>
                        <td>{!! $row->name !!}</td>
                        <td>{!! $row->url !!}</td>
                        <td>{!! $row->release_date !!}</td>
                        <td>{!! $row->closed_date !!}</td>
                        <td>
                            <a href="{!! route('fatorcms.popup.edit', $row->id) !!}" class="btn btn-xs btn-primary margin-right pull-left">
                                <i class="fa fa-pencil"></i>
                            </a>
                            {!! Form::open(['route' => ['fatorcms.popup.destroy', $row->id], 'onsubmit' => 'return false;', 'data-delete' => 'Deseja realmente deleta o popup: '. $row->name.'?', 'method' => 'DELETE', 'class' => 'form-horizontal pull-left']) !!}
                            <button data-toggle="tooltip" title="Excluir curso" class="btn no-rounded btn-danger btn-xs">
                                <i class="fa fa-trash-o"></i>
                            </button>
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@stop