modules/Acl/Http/routes.php
<?php

    Route::group([
        'prefix' => 'fatorcms',
        'middleware' => [
            'auth',
            'acl',
            'cms'
        ],
        'namespace'  => 'Modules\Acl\Http\Controllers'
    ], function () {
        Route::resource('/acl', 'AclController', [
            'only' => [
                'index',
                'store'
            ]
        ]);
        Route::patch('/acl/status/{id}', [
            'as'   => 'fatorcms.acl.status',
            'uses' => 'AclController@status'
        ]);

        Route::resource('/group', 'GroupController');
        Route::patch('/group/status/{id}', [
            'as'   => 'fatorcms.group.status',
            'uses' => 'GroupController@status'
        ]);
    });

modules/Acl/Entities/Group.php
<?php namespace Modules\Acl\Entities;

use App\BaseModel;

class Group extends BaseModel
{
    protected $fillable = [
        'parent_id',
        'name',
        'status'
    ];

    protected $appends = [
        'ParentGroup'
    ];

    public function getParentGroupAttribute()
    {
        if ($this->parent_id == 0) {
            $return = '---';
        } else {
            $return = Group::find($this->parent_id);
            $return = $return->name;
        }
        return $return;
    }

    private static function queryActionGrups($group, $request)
    {
        if ($request->get('action_id')) {
            $action_groups = [];
            foreach ($request->get('action_id') as $action_id) {
                $action_groups[] = new ActionGroup([
                    'action_id' => $action_id
                ]);
            }
            $group->action_groups()->saveMany($action_groups);
        }
    }

    /**
     * @param $request
     * Relaciona o grupo com as ações selecionadas
     */
    public static function customCreate($request)
    {
        $group = parent::firstOrCreate($request->except([
            '_token',
            'action_id'
        ]));
        ActionGroup::destroy($group->id);
        self::queryActionGrups($group, $request);
    }

    /**
     * @param $id
     * @param $request
     */
    public static function customUpdate($id, $request)
    {
        $group = Group::findOrFail($id);
        $group->update($request->except(['_token']));
        ActionGroup::destroy($id);
        self::queryActionGrups($group, $request);
    }

    public function groups()
    {
        return $this->belongsTo('Modules\Acl\Entities\Group', 'parent_id');
    }

    public function action_groups()
    {
        return $this->hasMany('Modules\Acl\Entities\ActionGroup', 'group_id');
    }

    public function actions()
    {
        return $this->belongsToMany('Modules\Acl\Entities\Action', 'action_groups', 'group_id', 'action_id');
    }
}

modules/Acl/Http/Controllers/GroupController.php
<?php namespace Modules\Acl\Http\Controllers;

use App\Http\Controllers\BaseModuleController;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;
use Modules\Acl\Entities\Action;
use Modules\Acl\Entities\ActionGroup;
use Modules\Acl\Entities\Group;
use Modules\Acl\Http\Requests\GroupRequest;

class GroupController extends BaseModuleController
{
    private function getArrayActions($id)
    {
        foreach (ActionGroup::where('group_id', '=', $id)->get(['action_id'])->toArray() as $value) {
            $actionsGroup[] = $value['action_id'];
        }
        View::share(compact('actionsGroup'));
    }

    /**
     * @return void
     */
    private function getActions()
    {
        if (Auth::user()->isAdmin()) {
            $actions = Action::with('parents')->whereParentId(0)->get();
        } else {
            $actions = Action::with(['parents' => function ($q) {
                $q->whereIn('id', Auth::user()->getActions('id'));
            }])->whereIn('id', Auth::user()->getActions('id'))->whereParentId(0)->get();
        }
        View::share(compact('actions'));
    }

    /**
     * @return View
     */
    public function index()
    {
        if (Auth::user() && !Auth::user()->isAdmin()) {
            $list = Group::with('groups')->whereParentId(Auth::user()->id)->orderBy('id', 'desc')->paginate(15);
        } else {
            $list = Group::orderBy('id', 'desc')->paginate(15);
        }
        return view('acl::group.index', compact('list'));
    }

    /**
     * @return View
     */
    public function create()
    {
        $this->getActions();
        return view('acl::group.create');
    }

    /**
     * @param GroupRequest $request
     * @return \Illuminate\Http\RedirectResponse
     * O parent_id será relacionado ao grupo do usuário logado
     */
    public function store(GroupRequest $request)
    {
        //Adicioanr group_id do usuário
        $request->merge(['parent_id' => Auth::user()->group_id]);
        Group::customCreate($request);
        return redirect()->route('fatorcms.group.index')->with('success', trans('messages.insert.success'));
    }

    /**
     * @param $id
     * @return View
     */
    public function edit($id)
    {
        $this->getActions();
        $this->getArrayActions($id);
        $edit = Group::findOrFail($id);
        return view('acl::group.edit', compact('edit'));
    }

    /**
     * @param GroupRequest $request
     * @param              $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(GroupRequest $request, $id)
    {
        //Adicioanr group_id do usuário
        $request->merge(['parent_id' => Auth::user()->group_id]);
        Group::customUpdate($id, $request);
        return redirect()->route('fatorcms.group.index')->with('success', trans('messages.update.success'));
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * Ativa ou Inativa o menu
     */
    public function status($id)
    {
        $status = Group::findOrFail($id);
        $to = ($status->status) ? 0 : 1;
        $status->status = $to;
        $status->save();
        return redirect()->route('fatorcms.group.index')->with('success', trans('messages.status.success', [
            'status' => ($to) ? trans('dictionary.status_text.active') : trans('dictionary.status_text.inactive')
        ]));
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        // Verifica se existe usuários relacionado ao grupo para deletar
        $users = User::whereGroupId($id)->first();
        if ($users) {
            $alert = [
                'type' => 'warning',
                'msg'  => trans('acl::db.messages.delete.warning')
            ];
        } else {
            $alert = [
                'type' => 'success',
                'msg'  => trans('acl::db.messages.delete.success')
            ];
        }
        Group::destroy($id);
        return redirect()->route('fatorcms.group.index')->with($alert['type'], $alert['msg']);
    }

}

modules/Acl/Resources/views/group/create.blade.php
@extends('layouts.cms')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h4 class="panel-title">{!! trans('dictionary.create') !!} {!! trans('dictionary.group') !!}</h4>
                <p>{!! trans('messages.form.alert.fields_required') !!}</p>
            </div>
        </div>
        {!! Form::open(['route' => 'fatorcms.group.store']) !!}
        @include('acl::group.form')
        {!! Form::close() !!}
    </div>
@endsection

modules/Acl/Resources/views/group/edit.blade.php
@extends('layouts.cms')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h4 class="panel-title">{!! trans('dictionary.edit') !!} {!! trans('dictionary.group') !!}</h4>
                <p>{!! trans('messages.form.alert.fields_required') !!}</p>
            </div>
        </div>
        {!! Form::model($edit, ['route' => ['fatorcms.group.update', $edit->id], 'method' => 'PATCH']) !!}
        @include('acl::group.form')
        {!! Form::close() !!}
    </div>
@endsection

modules/Acl/Resources/views/group/form.blade.php
<div class="col-lg-12">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <div class="form-group">
                <label for="status" class="control-label">{!! trans('dictionary.status') !!}</label>
                <br/>

                <div class="radio radio-success radio-inline">
                    {!! Form::radio('status', 1, true) !!}
                    <label for="radio4">
                        {!! trans('dictionary.status_text.active') !!}
                    </label>
                </div>
                <div class="radio radio-danger radio-inline">
                    {!! Form::radio('status', 0, false) !!}
                    <label for="radio4">
                        {!! trans('dictionary.status_text.inactive') !!}
                    </label>
                </div>
            </div>
            <div class="form-group {!! ($errors->first('name')) ? 'has-error' : '' !!}">
                <label for="name">{!! trans('dictionary.name'). ' (*)' !!}</label>
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('dictionary.name'). ' (*)', 'required' => 'required']) !!}
                {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="col-lg-12">
        <div class="panel">
            <div class="panel-body">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <th width="5%"></th>
                        <th>{!! trans('dictionary.name') !!}</th>
                        <th>{!! trans('dictionary.route') !!}</th>
                        <th width="5%">{!! trans('dictionary.status') !!}</th>
                        <th width="5%">{!! trans('dictionary.options') !!}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($actions as $action)
                        <tr>
                            <td>
                                {!! Form::checkbox('action_id[]', $action->id, null,
                                    [
                                        'title' => 'Selecionar módulo inteiro',
                                        'data-select-all' => $action->id,
                                        (isset($actionsGroup) && in_array($action->id,$actionsGroup)) ? 'checked' : ''
                                    ]
                                ) !!}
                            </td>
                            <td>{!! $action->name !!}</td>
                            <td>{!! $action->route !!}</td>
                            <td>{!! ($action->status) ? 'Ativo' : 'Inativo' !!}</td>
                            <td>
                                <div class="col-md-3">
                                    @if($action->parents->count() > 1)
                                        <i style="cursor: pointer;" class="fa fa-angle-double-down"
                                           data-arrow="{!! $action->id !!}"
                                           data-extend-action="{!! $action->id !!}"
                                           title="extender"></i>
                                    @endif
                                </div>
                            </td>
                        </tr>
                        @if($action->parents)
                            @foreach($action->parents as $sAction)
                                <tr style="display: none; background-color: #add8e6;"
                                    data-action-id="{!! $sAction->parent_id !!}">
                                    <td>
                                        {!! Form::checkbox('action_id[]', $sAction->id, null, ['data-action-id' => $sAction->parent_id, (isset($actionsGroup) && in_array($sAction->id,$actionsGroup)) ? 'checked' : '']) !!}
                                    </td>
                                    <td>{!! $sAction->name !!}</td>
                                    <td>{!! $sAction->route !!}</td>
                                    <td>{!! ($sAction->status) ? 'Ativo' : 'Inativo' !!}</td>
                                </tr>
                            @endforeach
                        @endif
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<div class="col-sm-12">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <button class="btn btn-success pull-right">{!! trans('menu::db.btn.submit') !!}</button>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

@section('cjs')
    {!! HTML::script('js/cms/acl/group.js') !!}
@endsection

modules/Acl/Resources/views/group/index.blade.php
@extends('layouts.cms')

@section('content')
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <a href="{!! URL::route('fatorcms.group.create') !!}" class="btn btn-success pull-right">
                {!! trans('dictionary.create') !!} {!! trans('dictionary.group') !!}
            </a>

            <h2>{!! trans('dictionary.group') !!}</h2>
        </div>
        <div class="ibox-content">

            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover datatable">
                    <thead>
                    <tr>
                        <th data-ref="name">{!! trans('dictionary.name') !!}</th>
                        <th data-ref="status">{!! trans('dictionary.status') !!}</th>
                        <th data-ref="created_at">{!! trans('dictionary.created_at') !!}</th>
                        <th width="11%">{!! trans('dictionary.options') !!}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if ($list->count())
                        @foreach($list as $row)
                            <tr>
                                <td>{!! $row->name !!}</td>
                                <td>{!! $row->statusText !!}</td>
                                <td>{!! $row->created_at !!}</td>
                                <td>
                                    <a class="btn btn-primary btn-xs pull-left margin-right"
                                       href="{!! URL::route('fatorcms.group.edit', $row->id) !!}">
                                        <i class="fa fa-pencil"></i>
                                    </a>

                                    {!! Form::open(['route' => ['fatorcms.group.status', $row->id], 'method' => 'PATCH', 'class' => 'form-horizontal pull-left']) !!}
                                    <button class="btn {!! ($row->status) ? 'btn-success' : 'btn-danger' !!} btn-xs margin-right"
                                            title="{!! $row->StatusText !!}">
                                        <i class="glyphicon {!! ($row->status) ? 'glyphicon-ok' : 'glyphicon-off' !!}"></i>
                                    </button>
                                    {!! Form::close() !!}

                                    {!! Form::open(['route' => ['fatorcms.group.destroy', $row->id], 'method' => 'DELETE', 'class' => 'form-horizontal pull-left']) !!}
                                    <button class="btn btn-danger btn-xs">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7">Nenhum registro encontrado.</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
                @include('layouts.elements.paginator', ['paginator' => $list])
            </div>

        </div>
    </div>
@endsection