modules/Order/Http/routes.php
<?php

    Route::group([
        'prefix'     => 'fatorcms',
        'middleware' => [
            'auth',
            'acl',
            'cms'
        ],
        'namespace'  => 'Modules\Order\Http\Controllers'
    ], function () {
        Route::get('order', [
            'as'   => 'fatorcms.order.index',
            'uses' => 'OrderController@index'
        ]);
        Route::get('order/{id}/show', [
            'as'   => 'fatorcms.order.show',
            'uses' => 'OrderController@show'
        ]);
        Route::get('order/search', [
            'uses' => 'OrderController@index',
            'as'   => 'fatorcms.order'
        ]);
        Route::resource('coupon', 'CouponController');
        Route::patch('/coupon/status/{id}', [
            'as'   => 'fatorcms.coupon.status',
            'uses' => 'CouponController@status'
        ]);

    });

    Route::get('/fatorcms/order/make/manual', [
        'middleware' => 'cms',
        'as'         => 'order.make.manual',
        'uses'       => 'Modules\Order\Http\Controllers\OrderController@manualOrder'
    ]);

    Route::post('/fatorcms/order/store/manual', [
        'middleware' => 'cms',
        'as'         => 'order.store.manual',
        'uses'       => 'Modules\Order\Http\Controllers\OrderController@postCreateManualOrder'
    ]);

    Route::post('/fatorcms/order/update/status/{id}', [
        'middleware' => 'cms',
        'as'         => 'order.status.update',
        'uses'       => 'Modules\Order\Http\Controllers\OrderController@updateStatus'
    ]);

modules/Order/Entities/Order.php
<?php namespace Modules\Order\Entities;

use App\BaseModel;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Modules\Team\Entities\Team;
use Modules\User\Entities\User;

/**
 *
 * @apiVersion    0.0.1
 * @api           {class} Order
 * @apiGroup      OrderModel
 *
 * @apiPermission Developers/Public
 *
 */
class Order extends BaseModel
{

    protected $fillable = [
        'user_id',
        'abandoned_order_id',
        'coupon',
        'discount',
        'fee_amount',
        'net_amount',
        'pagseguro_code',
        'pagseguro_type',
        'pagseguro_method_type',
        'pagseguro_method_code',
        'pagseguro_json',
        'pagseguro_status',
        'sub_total',
        'total',
        'notification_email',
        'filename',
        'payment_link',
        'payment_wait',
        'payment_reference_old',
        'created_at'
    ];

    protected $appends = ['UserEmail'];

    public $excel = [
        '#Identificação', 'E-mail', 'Cupom', 'Desconto', 'Sub Total', 'Total', 'Data de registro', 'Data de alteração no registro'
    ];

    public $excelModel = [
        'id', 'UserEmail', 'coupon', 'discount', 'sub_total', 'total', 'created_at', 'updated_at'
    ];

    public function getUserEmailAttribute()
    {
        $user = User::find($this->user_id);
        if ($user) {
            return $user->email;
        } else {
            return 'Sem e-mail';
        }
    }

    public function pagseguro()
    {
        return $this->hasOne('Modules\Order\Entities\PagseguroCode', 'code', 'pagseguro_method_code');
    }

    public function orderStatus()
    {
        return $this->belongsTo('Modules\Order\Entities\OrderStatus', 'pagseguro_status');
    }

    public function orderItems()
    {
        return $this->hasMany('Modules\Order\Entities\OrderItem', 'order_id');
    }

    public function abandoned()
    {
        return $this->belongsTo('Modules\Order\Entities\AbandonedOrder', 'abandoned_order_id');
    }

    public function historical()
    {
        return $this->hasMany('Modules\Order\Entities\OrderHistoricalStatus', 'order_id')->orderBy('created_at', 'desc');
    }

    public function user()
    {
        return $this->belongsTo('Modules\User\Entities\User', 'user_id');
    }


    /**
     *
     * @apiVersion    0.0.1
     * @api           {function} findWithSearch
     * @apiGroup      OrderModel
     *
     * @apiParam {Object} request Parâmetros de pesquisa ou vazio
     * @apiSuccess {Object} list Dados da tabela 'orders'
     *
     * @param $request
     * @return \Illuminate\Database\Eloquent\Collection|static[]
     */
    public static function findWithSearch($request)
    {
        $get = Order::with(['user']);
        if (!static::verifyIfNotEmpty($request))
            return Order::orderBy('created_at', 'desc');
        if ($request->get('user_id'))
            $get->where('user_id', '=', $request->get('user_id'));
        if ($request->get('created_at'))
            $get->whereRaw('DATE(`created_at`) >= DATE(?)', [Carbon::createFromFormat('d-m-Y', $request->get('created_at'))->toDateString()]);
        else {
            $get->whereMonth('created_at', '=', date('m'))->whereYear('created_at', '=', date('Y'))->orderBy('created_at', 'desc');
        }
        if ($request->get('updated_at'))
            $get->where('updated_at', '<=', Carbon::createFromFormat('d-m-Y', $request->get('updated_at'))->toDateString());
        if ($request->get('order_id'))
            $get->where('id', '=', $request->get('order_id'));
        if ($request->get('order_status'))
            $get->where('pagseguro_status', '=', $request->get('order_status'));
        if ($request->get('product'))
            $get->whereIn('id', self::searchByProduct($request->get('product')));
        return $get;
    }

    private static function searchByProduct($product_id)
    {
        $teams = Team::where('course_id', '=', $product_id)->lists('id', 'id')->toArray();
        if ($teams) {
            $order_items = OrderItem::whereIn('ref', $teams)->lists('order_id', 'order_id')->toArray();
            if ($order_items) {
                return Order::whereIn('id', $order_items)->lists('id', 'id')->toArray();
            }
        }
        return null;
    }

    /**
     * @param $request
     * @return bool
     */
    private static function verifyIfNotEmpty($request)
    {
        if ($request->get('created_at') || $request->get('updated_at') || $request->get('order_id') || $request->get('order_status') || $request->get('user_id') || $request->get('product'))
            return true;
        return false;
    }

}

modules/Order/Http/Controllers/OrderController.php
<?php namespace Modules\Order\Http\Controllers;

use App\Http\Controllers\BaseModuleController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Modules\Order\Entities\AbandonedOrder;
use Modules\Order\Entities\AbandonedOrderItem;
use Modules\Order\Entities\Order;
use Modules\Order\Entities\OrderHistoricalStatus;
use Modules\Order\Entities\OrderItem;
use Modules\Order\Entities\OrderStatus;
use Modules\Order\Http\Requests\OrderSearchRequest;
use Modules\Team\Entities\Team;
use Modules\Team\Entities\TeamUser;
use Modules\User\Entities\User;

/**
 *
 * @apiVersion     0.0.1
 * @api            {class} OrderController
 * @apiGroup       Order
 * @apiDescription Controlador do módulo de pedidos do usuário. <br />
 *                 Ao inserir o módulo no projeto verificar os seguintes itens no projeto principal <br />
 *                 1 uma classe <code>ModuleController</code> <br />
 *                 2 uma classe <code>BaseController</code> <br />
 *                 Tabelas envolvidas <br />
 *                 <code>orders</code>,<code>order_statuses</code>,<code>order_items</code>,<code>order_historical_statuses</code>
 *
 *
 * Class OrderController
 * @package        Modules\Order\Http\Controllers
 */
class OrderController extends BaseModuleController
{

    private function lists()
    {
        $users = User::where('group_id', '!=', '1')->get()->lists('name_email', 'id')->toArray();
        $orderStatus = OrderStatus::all()->lists('name', 'id')->toArray();
        View::share(compact('orderStatus', 'users'));
    }

    /**
     *
     * @apiVersion    0.0.1
     * @api           {get} /order/:search OrderController:index
     * @apiGroup      Order
     *
     * @apiParam {Object} request Parâmetros de pesquisa ou vazio
     * @apiSuccess {Object} list Dados da tabela 'orders'
     * @apiPermission Developers/Public
     *
     * @param OrderSearchRequest $request
     * @return View
     */
    public function index(OrderSearchRequest $request)
    {
        $this->lists();
        $list = Order::findWithSearch($request);

        if (request()->has('export')) {
            $data = [];
            $items = $list->with('user')->get();
            $sub_total = $total = $taxa = $total_taxa = 0;
            foreach ($items as $item) {
                $pagseguro = json_decode($item->pagseguro_notification);
                $data[] = [
                    '#ID Pedido' => $item->id,
                    'Nome' => $item->user ? $item->user->name : '-',
                    'Pedido Status' => $item->orderStatus ? $item->orderStatus->name : '',
                    'E-mail' => $item->user ? $item->user->email : '-',
                    'Subtotal' => 'R$ ' . bcoToCoin($item->sub_total),
                    'Total' => 'R$ ' . bcoToCoin($item->total),
                    'Total Taxa' => 'R$ '.bcoToCoin($item->fee_amount),
                    'Total com taxa Pagseguro' => 'R$ '.bcoToCoin($item->net_amount),
                    'Data & Hora' => dateToSql($item->created_at, 'Y-m-d H:i:s', 'd/m/Y H:i:s')
                ];
                $sub_total += $item->sub_total;
                if ($item->pagseguro_status == 3 || $item->pagseguro_status == 4)
                    $total += $item->total;
                if ($item->pagseguro_status == 3 || $item->pagseguro_status == 4) {
                    $taxa += $item->fee_amount;
                    $total_taxa += $item->net_amount;
                }
            }
            $this->export_excel($data, 'Pedidos', [
                '#ID Pedido',
                'Nome',
                'Pedido Status',
                'E-mail',
                'Subtotal',
                'Total',
                'Total Taxa',
                'Total com taxa Pagseguro',
                'Data & Hora'
            ], [
                '',
                '',
                '',
                '',
                'Subtotal',
                'Total Pago',
                'Total Taxa',
                'Total Pago com taxa Pagseguro',
                ''
            ], [[
                '',
                '',
                '',
                '',
                'R$ '. bcoToCoin($sub_total),
                'R$ '. bcoToCoin($total),
                'R$ '. bcoToCoin($taxa),
                'R$ '. bcoToCoin($total_taxa),
                ''
            ]]);
        }

        $list = $list->paginate(50);

        return view('order::order.index', compact('list'));
    }

    /**
     *
     * @apiVersion    0.0.1
     * @api           {get} /order/:order_id OrderController:show
     * @apiGroup      Order
     * @apiSuccess {Object} show Dados referente ao id do pedido
     * @apiError      OrderNotFound <code>id</code> da tabela orders.
     * @apiPermission Developers/Public
     *
     * @param $id
     * @return View
     */
    public function show($id)
    {
        $statuses = OrderStatus::all()->lists('name', 'id')->toArray();
        $show = Order::with(['user', 'abandoned', 'historical', 'orderItems'])->find($id);
        return view('order::order.show', compact('show', 'statuses'));
    }

    public function updateStatus(Request $request, $id)
    {
        $order = Order::find($id);
        if ($order) {

            $order->update(['pagseguro_status' => $request->get('pagseguro_status')]);
            OrderHistoricalStatus::create([
                'order_id' => $id,
                'order_status_id' => $request->get('pagseguro_status')
            ]);
            $orderItem = OrderItem::whereOrderId($id)->get();
            if ($request->get('pagseguro_status') == 3 || $request->get('pagseguro_status') == 4) {
                foreach ($orderItem as $item) {
                    $team = Team::whereId($item->ref)->orderBy('id', 'desc')->first();
                    if ($team) {
                        $end_days = $team->end_days ? date('Y-m-d', strtotime('+' . $team->end_days . ' days')) : null;
                        TeamUser::firstOrCreate([
                            'course_id' => $team->course_id,
                            'team_id' => $team->id,
                            'user_id' => $order->user_id,
                            'end_date' => $end_days
                        ]);
                    } else {
                        return redirect()->back()->with('error', 'Ops, houve um erro inesperado. Tente novamente.');
                    }
                }
            } else {
                foreach ($orderItem as $item) {
                    $userinteam = TeamUser::whereUserId($order->user_id)->whereTeamId($item->ref)->first();
                    if ($userinteam) {
                        $userinteam->delete();
                    }
                }
            }

        }
        return redirect()->route('fatorcms.order.show', $id)->with('success', 'Pedido Atualizado');
    }

    /**
     * @return View
     */
    public function manualOrder()
    {
        $this->lists();
        return view('order::order.make_order');
    }

    public function postCreateManualOrder(Request $request)
    {
        $user = User::find($request->get('user_id'));
        $module = Team::find($request->get('team_id'));

        $abandoned = AbandonedOrder::create([
            'user_id' => $user->id,
            'total' => $module->value_discount > 0 ? $module->value_discount : $module->value,
            'sub_total' => $module->value,
            'transaction_json' => 'MANUALMENTE',
            'finished' => true
        ]);

        $abandoned_item = AbandonedOrderItem::create([
            'order_id' => $abandoned->id,
            'code' => 'Modules\Team\Entities\Team#' . $module->id,
            'value' => $abandoned->total
        ]);

        $order = Order::create([
            'user_id' => $abandoned->user_id,
            'abandoned_order_id' => $abandoned->id,
            'pagseguro_method_code' => $request->get('pagseguro_method_code'),
            'total' => $abandoned->total,
            'sub_total' => $abandoned->total,
            'payment_link' => 'http://google.com.br'
        ]);

        $order_item = OrderItem::create([
            'name' => $module->name,
            'order_id' => $order->id,
            'ref' => $module->id,
            'value' => $module->value,
            'quantity' => 1
        ]);


        $historical = OrderHistoricalStatus::create([
            'order_id' => $order->id,
            'order_status_id' => 1
        ]);

        return redirect()->route('fatorcms.order.show', $order->id)->with('success', 'O pedido foi gerado com sucesso.');
    }

}

modules/Order/Resources/views/order/index.blade.php
@extends('layouts.cms')

@section('content')


    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <a href="{!! URL::route('fatorcms.coupon.create') !!}"
               class="btn btn-success pull-right">
                {!! trans('dictionary.coupon') !!}
            </a>
            <h2>{!! trans('dictionary.order_v') !!}</h2>
        </div>
        <div class="ibox-content">
            {!! Form::open(['url' => 'fatorcms/order/search', 'method' => 'GET']) !!}
            <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group {!! ($errors->first('order_id')) ? 'has-error' : ''  !!}">
                            <label class="control-label"
                                   for="order_id">
                                {!! trans('dictionary.order_id') !!}
                            </label>
                            {!! Form::text('order_id', Input::get('order_id'), ['id' => 'order_id', 'data-column-id' => '0', 'name' => 'order_id', 'class' => 'form-control', 'placeholder' => trans('dictionary.order_id')]) !!}
                            {!! $errors->first('order_id', '<span class="help-block">:message</span>') !!}
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group {!! ($errors->first('order_status')) ? 'has-error' : ''  !!}">
                            <label class="control-label"
                                   for="status">
                                {!! trans('dictionary.order_status.title') !!}
                            </label>
                            {!! Form::select('order_status', ['' => trans('dictionary.select', ['name' => trans('dictionary.order_status.title')])] + $orderStatus, Input::get('order_status'), [ 'class' => 'form-control']) !!}
                            {!! $errors->first('order_status', '<span class="help-block">:message</span>') !!}
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group {!! ($errors->first('user_id')) ? 'has-error' : ''  !!}">
                            <label class="control-label"
                                   for="customer">
                                {!! trans('dictionary.user') !!}
                            </label>
                            {!! Form::select('user_id', ['' => trans('dictionary.select', ['name' => trans('dictionary.user')])] + $users, Input::get('user_id'), [ 'data-column-id' => '1', 'class' => 'form-control select']) !!}
                            {!! $errors->first('user_id', '<span class="help-block">:message</span>') !!}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group {!! ($errors->first('created_at')) ? 'has-error' : ''  !!}">
                            <label class="control-label"
                                   for="date_added">
                                {!! trans('dictionary.created_at') !!}
                            </label>
                            <div class="input-group date">
                                <span class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </span>
                                {!! Form::text('created_at', Input::get('created_at'), ['class' => 'form-control date-mask-us', 'maxlength' => '10', 'placeholder' => 'Todos os dias']) !!}
                            </div>
                            {!! $errors->first('created_at', '<span class="help-block">:message</span>') !!}
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group {!! ($errors->first('updated_at')) ? 'has-error' : ''  !!}">
                            <label class="control-label"
                                   for="date_modified">
                                {!! trans('dictionary.updated_at') !!}
                            </label>
                            <div class="input-group date">
                                <span class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </span>
                                {!! Form::text('updated_at', Input::get('updated_at'), ['class' => 'form-control date-mask-us', 'placeholder' => 'Todos os dias', 'maxlength' => '10']) !!}
                            </div>
                            {!! $errors->first('updated_at', '<span class="help-block">:message</span>') !!}
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group {!! ($errors->first('product')) ? 'has-error' : ''  !!}">
                            <label class="control-label"
                                   for="product">
                                Curso
                            </label>
                            {!! Form::select('product', ['' => 'Selecione o curso que procura'] + \Modules\Course\Entities\Course::lists('name', 'id')->toArray(), Input::get('product'), ['class' => 'form-control']) !!}
                            {!! $errors->first('product', '<span class="help-block">:message</span>') !!}
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <br />
                            <button type="submit" class="btn btn-info" title="{!! trans('dictionary.search') !!}">
                                <i class="fa fa-search"></i> Procurar
                            </button>
                            <a href="{!! URL::route('fatorcms.order.index') !!}" title="{!! trans('dictionary.clear') !!}" class="btn btn-success">
                                <i class="fa fa-eraser"></i> Limpar
                            </a>
                            <a href="{!! URL::route('order.make.manual') !!}" title="Criar pedido manualmente" class="btn btn-default">
                                <i class="fa fa-plus"></i> Gerar pedido
                            </a>
                            <a href="{!! route('fatorcms.order.index', 'export=true&' . request()->getQueryString()) !!}" class="btn btn-primary">
                                Exportar
                            </a>
                        </div>
                    </div>

                </div>
            {!! Form::close() !!}

            <div class="table-responsive">
                <table id="commerceTable"
                       class="table table-bordered">
                    <thead>
                    <tr>
                        <th data-ref="id">{!! trans('dictionary.order_id') !!}</th>
                        <th data-ref="user_id">{!! trans('dictionary.user') !!}</th>
                        <th data-ref="coupon">Status</th>
                        <th data-ref="discount">{!! trans('dictionary.discount') !!}</th>
                        <th data-ref="sub_total">{!! trans('dictionary.sub_total') !!}</th>
                        <th data-ref="total">{!! trans('dictionary.total') !!}</th>
                        <th data-ref="notification_email">{!! trans('dictionary.notified') !!}</th>
                        <th data-ref="created_at">{!! trans('dictionary.created_at') !!}</th>
                        <th data-ref="updated_at">{!! trans('dictionary.updated_at') !!}</th>
                        <th width="11%">{!! trans('dictionary.options') !!}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if ($list->count())
                        @foreach($list as $row)
                            <tr>
                                <td>{!! $row->id !!}</td>
                                <td>{!! (!is_null($row->user)) ? $row->user->name . ' - ' . $row->user->email  : 'USUÁRIO NÃO EXISTENTE' !!}</td>
                                <td>{!! (!is_null($row->orderStatus)) ? $row->orderStatus->name : 'DADOS INDISPONÍVEIS' !!}</td>
                                <td>{!! $row->discount !!}</td>
                                <td>{!! $row->sub_total !!}</td>
                                <td>{!! $row->total !!}</td>
                                <td>{!! $row->notification_email !!}</td>
                                <td>{!! \Carbon\Carbon::parse($row->created_at)->format('d/m/Y H:i:s') !!}</td>
                                <td>{!! \Carbon\Carbon::parse($row->updated_at)->format('d/m/Y H:i:s') !!}</td>
                                <td>
                                    <a href="{!! URL::route('fatorcms.order.show', $row->id) !!}" class="btn btn-success" title="{!! trans('dictionary.view') !!}">
                                        <i class="fa fa-align-justify"></i>
                                    </a>
                                </td>
                            </tr>
                            @if ($row->OrderItems)
                                <tr class="bg-danger">
                                    <td colspan="5">Curso</td>
                                    <td colspan="4">Valor</td>
                                    <td>Quantidade</td>
                                </tr>
                                @foreach($row->OrderItems as $item)
                                    <tr class="bg-primary">
                                        <td colspan="5">{!! $item->name !!}</td>
                                        <td colspan="4">{!! $item->value !!}</td>
                                        <td>{!! $item->quantity !!}</td>
                                    </tr>
                                @endforeach
                            @endif
                        @endforeach
                    @endif
                    </tbody>
                </table>
                @include('layouts.elements.paginator', ['paginator' => $list])
            </div>

        </div>
    </div>
@endsection

modules/Order/Resources/views/order/make_order.blade.php
@extends('layouts.cms')

@section('title')
  <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Novo Pedido</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{!! route('fatorcms.dashboard') !!}">Dashboard</a>
            </li>
            <li>
                <a href="{!! route('fatorcms.order.index') !!}">Pedidos</a>
            </li>
            <li class="active">
                <strong>Novo Pedido</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-12">
      <p>
        Todos os campos com <strong class="text-danger">(*)</strong> são obrigatórios.
      </p>
    </div>
  </div>

  <div class="row page-heading white-bg">
    <div class="col-lg-9">
        <br/>
        <a href="{!! URL::route('fatorcms.team.index') !!}"
           class="btn btn-warning">
            Voltar
        </a>
    </div>
  </div>
@endsection

@section('content')

  <div class="row">
    <div class="col-lg-12">
        <div class="ibox-title">
            <h4 class="panel-title">
                {!! trans('dictionary.create') !!} Pedido Manualmente
            </h4>
            <p>{!! trans('messages.form.alert.fields_required') !!}</p>
        </div>
    </div>
    {!! Form::open(['route' => 'order.store.manual']) !!}
    <div class="col-lg-12">
          <div class="ibox">
              <div class="ibox-content  float-e-margins">
                  <div class="form-group {!! ($errors->first('user_id')) ? 'has-error' : ''  !!}">
                      <label class="control-label"
                             for="customer">
                          Usuário <strong class="text-danger">(*)</strong>
                      </label>
                    {!! Form::select('user_id', ['' => trans('dictionary.select', ['name' => 'Usuário'])] + $users, Input::get('user_id'), [
                    'class' => 'form-control select', 'required']) !!}
                    {!! $errors->first('user_id', '<span class="help-block">:message</span>') !!}
                  </div>

                  <div class="form-group">
                      <label for="module_id">
                          Turma
                      </label>
                    {!! Form::select('team_id', ['' => 'Selecione a Turma'] + \Modules\Team\Entities\Team::all()->lists('name', 'id')->toArray(), Input::get('team_id'), ['class' => 'form-control select']) !!}
                    {!! $errors->first('team_id', '<span class="help-block">:message</span>') !!}
                  </div>

                  <div class="row">
                      <div class="col-lg-6">
                          <div class="form-group">
                              <label for="">
                                  Valor
                              </label>
                              {!! Form::text('value', null, ['class' => 'form-control money', 'placeholder' => '0,00']) !!}
                              {!! $errors->first('value', '<span class="help-block">:message</span>') !!}
                          </div>
                      </div>
                      <div class="col-lg-6">
                          <div class="form-group">
                              <label for="">
                                  Valor de desconto
                              </label>
                              {!! Form::text('discount', null, ['class' => 'form-control money', 'placeholder' => '0,00']) !!}
                              {!! $errors->first('discount', '<span class="help-block">:message</span>') !!}
                          </div>
                      </div>
                  </div>

                  <div class="form-group">
                      <label for="module_id">
                          Forma de pagamento <strong class="text-danger">(*)</strong>
                      </label>
                    {!! Form::select('pagseguro_method_code', ['' => 'Selecione a forma de pagamento'] + \Modules\Order\Entities\PagseguroCode::all()->lists('name', 'code')->toArray(), Input::get('team_id'), ['class' => 'form-control select', 'required']) !!}
                    {!! $errors->first('pagseguro_method_code', '<span class="help-block">:message</span>') !!}
                  </div>

                  <div class="form-group">
                      <button type="submit"
                              class="btn btn-success pull-right">
                          Criar Pedido
                      </button>
                      <div class="clearfix"></div>
                  </div>

              </div>
          </div>
      </div>
  </div>
  {!! Form::close() !!}
@endsection